/* market-data.js — GENERATED by tools/build-market.mjs from data/market/*.csv
   Do not hand-edit; edit the CSVs and re-run `node tools/build-market.mjs`.
   Integer engine units (1 in = 24384). tier: 0 mass · 1 mid · 2 upper.
   dining points carry a 4th field — state: 0 fixed · 1 closed · 2 extended. */
(function (root, factory) {
  var mod = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = mod;
  else { root.MarketData = mod; }
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  return { snapshot: null, classes: {} };
});
